---
- hosts: pi
  become: true
  gather_facts: false

  vars_files:
    - config.yml

  pre_tasks:
    - name: Ensure git is installed.
      package: name=git state=present
    - name: Ensure autoconf  is installed.
      package: name=autoconf  state=present
    - name: Ensure libtool is installed.
      package: name=libtool state=present
    - name: Ensure libusb-dev is installed.
      package: name=libusb-dev state=present
      
  tasks:
    - include_tasks: tasks/boot-config.yml
    - include_tasks: tasks/openocd.yml
