---
- name: Clone OpenOCD to the Pi.
  git:
    repo: "{{ openocd_repo }}"
    dest: /home/pi/openocd-code
    version: "{{ openocd_repo_version }}"
  become: false

- name: OpenOCD Install - Bootstrap
  command: bootstrap
  args:
    chdir: /home/pi/openocd-code
  become: false

- name: OpenOCD Install - Configure
  command: configure --enable-bcm2835gpio --enable-cmsis-dap --enable-sysfsgpio
  args:
    chdir: /home/pi/openocd-code
  become: false

- name: Build Open-OCD.
  make:
    chdir: /home/pi/openocd-code
  become: false

- name: Install Open-OCD.
  make:
    chdir: /home/pi/openocd-code
    target: install
  become: true
  